import {
  Facebook,
  Instagram,
  Twitter,
  LinkedIn,
  YouTube,
} from "@mui/icons-material";

// footer data
// export const footerData = [
//   {
//     id: 1,
//     title: "Web Design",
//     subCategory: [
//       { id: 1, title: "HTML / CSS / SASS" },
//       { id: 2, title: "PSD to HTML" },
//       { id: 3, title: "PSD to Wordpress" },
//       { id: 4, title: "JavaScript / jQuery" },
//       { id: 5, title: "React / Vue / Angular" },
//       { id: 6, title: "Bootstrap4" },
//       { id: 7, title: "Ember / Backbone" },
//     ],
//   },
//   {
//     id: 2,
//     title: "Web Development",
//     subCategory: [
//       { id: 1, title: "PHP" },
//       { id: 2, title: "Node.js" },
//       { id: 3, title: "Ruby" },
//       { id: 4, title: "WordPress Development" },
//       { id: 5, title: "Python" },
//       { id: 6, title: "Java" },
//       { id: 7, title: ".NET" },
//     ],
//   },
//   {
//     id: 3,
//     title: "App Development",
//     subCategory: [
//       { id: 1, title: "iPhone" },
//       { id: 2, title: "Android" },
//       { id: 3, title: "Hybrid" },
//       { id: 4, title: "Windows" },
//       { id: 5, title: "PhoneGap" },
//       { id: 6, title: "React Native" },
//       { id: 7, title: "IoT Development" },
//     ],
//   },
//   {
//     id: 4,
//     title: "Digital Marketing",
//     subCategory: [
//       { id: 1, title: "Search Engine Optimization" },
//       { id: 2, title: "Social Media Marketing" },
//       { id: 3, title: "Search Engine Marketing" },
//       { id: 4, title: "Pay-Per-Click Advertising" },
//       { id: 5, title: "Content Marketing" },
//       { id: 6, title: "Affiliate Marketing" },
//       { id: 7, title: "Local SEO" },
//     ],
//   },
//   {
//     id: 5,
//     title: "Graphic & Animation",
//     subCategory: [
//       { id: 1, title: "UI/UX Design" },
//       { id: 2, title: "Logo Design" },
//       { id: 3, title: "Product & Info Graphic Design" },
//       { id: 4, title: "Illustration" },
//       { id: 5, title: "2D Explainer Video" },
//       { id: 6, title: "3D Explainer Video" },
//       { id: 7, title: "White Board Animation" },
//     ],
//   },
//   {
//     id: 6,
//     title: "E-commerce Solution",
//     subCategory: [
//       { id: 1, title: "WordPress - Woocommerce" },
//       { id: 2, title: "OpenCart" },
//       { id: 3, title: "Shopify" },
//       { id: 4, title: "Magento" },
//       { id: 5, title: "PHP / Laravel / CodeIgniter" },
//       { id: 6, title: "BigCommerce" },
//       { id: 7, title: "Python / Django" },
//     ],
//   },
//   {
//     id: 7,
//     title: "Emerging Technologies",
//     subCategory: [
//       { id: 1, title: "Artificial Intelligence" },
//       { id: 2, title: "Deep Learning" },
//       { id: 3, title: "Big Data" },
//       { id: 4, title: "Machine Learning" },
//       { id: 5, title: "Internet of Things (IoT)" },
//       { id: 6, title: "Cloud Computing" },
//       { id: 7, title: "Quantum Technology" },
//     ],
//   },
//   {
//     id: 8,
//     title: "Cyber Security",
//     subCategory: [
//       { id: 1, title: "Website Security" },
//       { id: 2, title: "Phishing Protection" },
//       { id: 3, title: "Data Security" },
//       { id: 4, title: "Application Security" },
//       { id: 5, title: "Identity Security" },
//       { id: 6, title: "Ethical Hacking" },
//     ],
//   },
// ];

// social media
export const socialMedia = [
  {
    id: 1,
    name: "Facebook",
    icon: <Facebook />,
    link: "https://www.instagram.com/skool.saver/",
    color: "#4267B2",
  },
  {
    id: 2,
    name: "Instagram",
    icon: <Instagram />,
    link: "https://www.instagram.com/skool.saver/",
    color: "#E1306C",
  },
  // {
  //   id: 3,
  //   name: "Twitter",
  //   icon: <Twitter />,
  //   link: "https://www.twitter.com",
  //   color: "#1DA1F2",
  // },
  {
    id: 4,
    name: "LinkedIn",
    icon: <LinkedIn />,
    link: "https://www.linkedin.com/company/skoolsaver/",
    color: "#0077B5",
  },
  // {
  //   id: 5,
  //   name: "YouTube",
  //   icon: <YouTube />,
  //   link: "https://www.youtube.com",
  //   color: "#FF0000",
  // },
];

// experience options
export const experienceOptions = [
  { id: 0, experience: "fresher" },
  { id: 1, experience: "1 year" },
  { id: 2, experience: "2 years" },
  { id: 3, experience: "3 years" },
  { id: 4, experience: "4 years" },
  { id: 5, experience: "5 years" },
  { id: 6, experience: "6 years" },
  { id: 7, experience: "7 years" },
  { id: 8, experience: "8 years" },
  { id: 9, experience: "9 years" },
  { id: 10, experience: "10 years" },
  { id: 11, experience: "11 years" },
  { id: 12, experience: "12 years" },
  { id: 13, experience: "13 years" },
  { id: 14, experience: "14 years" },
  { id: 15, experience: "15 years" },
  { id: 16, experience: "16 years" },
  { id: 17, experience: "17 years" },
  { id: 18, experience: "18 years" },
  { id: 19, experience: "19 years" },
  { id: 20, experience: "20 years" },
  { id: 21, experience: "21 years" },
  { id: 22, experience: "22 years" },
  { id: 23, experience: "23 years" },
  { id: 24, experience: "24 years" },
  { id: 25, experience: "25 years" },
  { id: 26, experience: "26 years" },
  { id: 27, experience: "27 years" },
  { id: 28, experience: "28 years" },
  { id: 29, experience: "29 years" },
  { id: 30, experience: "30 years" },
  { id: 31, experience: "31 years" },
  { id: 32, experience: "32 years" },
  { id: 33, experience: "33 years" },
  { id: 34, experience: "34 years" },
  { id: 35, experience: "35 years" },
  { id: 36, experience: "36 years" },
  { id: 37, experience: "37 years" },
  { id: 38, experience: "38 years" },
  { id: 39, experience: "39 years" },
  { id: 40, experience: "40 years" },
  { id: 41, experience: "41 years" },
  { id: 42, experience: "42 years" },
  { id: 43, experience: "43 years" },
  { id: 44, experience: "44 years" },
  { id: 45, experience: "45 years" },
  { id: 46, experience: "46 years" },
  { id: 47, experience: "47 years" },
  { id: 48, experience: "48 years" },
  { id: 49, experience: "49 years" },
  { id: 50, experience: "50 years" },
];

export const skillOptions = [
  { id: 1, skill: "Data Analysis" },
  { id: 2, skill: "JavaScript" },
  { id: 3, skill: "Python" },
  { id: 4, skill: "Project Management" },
  { id: 5, skill: "Machine Learning" },
  { id: 6, skill: "React" },
  { id: 7, skill: "Cybersecurity" },
  { id: 8, skill: "Leadership" },
  { id: 9, skill: "AWS" },
  { id: 10, skill: "Blockchain" },
  { id: 11, skill: "Problem Solving" },
  { id: 12, skill: "SQL" },
  { id: 13, skill: "Communication" },
  { id: 14, skill: "Docker" },
  { id: 15, skill: "Kubernetes" },
  { id: 16, skill: "Teamwork" },
  { id: 17, skill: "Cloud Computing" },
  { id: 18, skill: "UI/UX Design" },
  { id: 19, skill: "Linux" },
  { id: 20, skill: "DevOps" },
  { id: 21, skill: "Java" },
  { id: 22, skill: "Sales" },
  { id: 23, skill: "HTML" },
  { id: 24, skill: "CSS" },
  { id: 25, skill: "Angular" },
  { id: 26, skill: "Node.js" },
  { id: 27, skill: "Express.js" },
  { id: 28, skill: "MongoDB" },
  { id: 29, skill: "PostgreSQL" },
  { id: 30, skill: "Customer Service" },
  { id: 31, skill: "Financial Analysis" },
  { id: 32, skill: "Risk Management" },
  { id: 33, skill: "Agile Methodology" },
  { id: 34, skill: "Scrum" },
  { id: 35, skill: "Trello" },
  { id: 36, skill: "Jira" },
  { id: 37, skill: "Confluence" },
  { id: 38, skill: "Product Management" },
  { id: 39, skill: "Market Research" },
  { id: 40, skill: "SEO" },
  { id: 41, skill: "SEM" },
  { id: 42, skill: "Content Marketing" },
  { id: 43, skill: "Social Media Marketing" },
  { id: 44, skill: "Email Marketing" },
  { id: 45, skill: "Branding" },
  { id: 46, skill: "Graphic Design" },
  { id: 47, skill: "Adobe Photoshop" },
  { id: 48, skill: "Adobe Illustrator" },
  { id: 49, skill: "Video Editing" },
  { id: 50, skill: "Motion Graphics" },
  { id: 51, skill: "3D Modeling" },
  { id: 52, skill: "AutoCAD" },
  { id: 53, skill: "SketchUp" },
  { id: 54, skill: "Revit" },
  { id: 55, skill: "Interior Design" },
  { id: 56, skill: "Architecture" },
  { id: 57, skill: "Construction Management" },
  { id: 58, skill: "Civil Engineering" },
  { id: 59, skill: "Mechanical Engineering" },
  { id: 60, skill: "Electrical Engineering" },
  { id: 61, skill: "Chemical Engineering" },
  { id: 62, skill: "Mathematics" },
  { id: 63, skill: "Statistics" },
  { id: 64, skill: "Physics" },
  { id: 65, skill: "Biology" },
  { id: 66, skill: "Chemistry" },
  { id: 67, skill: "Environmental Science" },
  { id: 68, skill: "Geology" },
  { id: 69, skill: "Astrophysics" },
  { id: 70, skill: "Artificial Intelligence" },
  { id: 71, skill: "Deep Learning" },
  { id: 72, skill: "Neural Networks" },
  { id: 73, skill: "NLP (Natural Language Processing)" },
  { id: 74, skill: "Data Mining" },
  { id: 75, skill: "Data Warehousing" },
  { id: 76, skill: "ETL (Extract, Transform, Load)" },
  { id: 77, skill: "Data Visualization" },
  { id: 78, skill: "Power BI" },
  { id: 79, skill: "Tableau" },
  { id: 80, skill: "Business Intelligence" },
  { id: 81, skill: "SAP" },
  { id: 82, skill: "Oracle" },
  { id: 83, skill: "ERP Systems" },
  { id: 84, skill: "Supply Chain Management" },
  { id: 85, skill: "Logistics" },
  { id: 86, skill: "Inventory Management" },
  { id: 87, skill: "Procurement" },
  { id: 88, skill: "Vendor Management" },
  { id: 89, skill: "Human Resources" },
  { id: 90, skill: "Recruitment" },
  { id: 91, skill: "Onboarding" },
  { id: 92, skill: "Employee Relations" },
  { id: 93, skill: "Compensation & Benefits" },
  { id: 94, skill: "Talent Management" },
  { id: 95, skill: "Learning & Development" },
  { id: 96, skill: "Employee Training" },
  { id: 97, skill: "Performance Management" },
  { id: 98, skill: "HR Compliance" },
  { id: 99, skill: "Labor Laws" },
  { id: 100, skill: "Diversity & Inclusion" },
  { id: 101, skill: "Employee Engagement" },
  { id: 102, skill: "Conflict Resolution" },
  { id: 103, skill: "Mediation" },
  { id: 104, skill: "Negotiation" },
  { id: 105, skill: "Time Management" },
  { id: 106, skill: "Stress Management" },
  { id: 107, skill: "Adaptability" },
  { id: 108, skill: "Creativity" },
  { id: 109, skill: "Critical Thinking" },
  { id: 110, skill: "Decision Making" },
  { id: 111, skill: "Organizational Skills" },
  { id: 112, skill: "Attention to Detail" },
  { id: 113, skill: "Problem Solving" },
  { id: 114, skill: "Presentation Skills" },
  { id: 115, skill: "Public Speaking" },
  { id: 116, skill: "Collaboration" },
  { id: 117, skill: "Interpersonal Skills" },
  { id: 118, skill: "Multitasking" },
  { id: 119, skill: "Innovation" },
  { id: 120, skill: "Entrepreneurship" },
  { id: 121, skill: "Business Development" },
  { id: 122, skill: "Strategic Planning" },
  { id: 123, skill: "Financial Management" },
  { id: 124, skill: "Budgeting" },
  { id: 125, skill: "Forecasting" },
  { id: 126, skill: "Accounting" },
  { id: 127, skill: "Auditing" },
  { id: 128, skill: "Taxation" },
  { id: 129, skill: "Payroll" },
  { id: 130, skill: "Bookkeeping" },
  { id: 131, skill: "Cost Management" },
  { id: 132, skill: "Financial Reporting" },
  { id: 133, skill: "Investment Analysis" },
  { id: 134, skill: "Risk Assessment" },
  { id: 135, skill: "Wealth Management" },
  { id: 136, skill: "Portfolio Management" },
  { id: 137, skill: "Capital Markets" },
  { id: 138, skill: "Real Estate" },
  { id: 139, skill: "Insurance" },
  { id: 140, skill: "Pension Management" },
  { id: 141, skill: "Healthcare Management" },
  { id: 142, skill: "Medical Billing" },
  { id: 143, skill: "Clinical Research" },
  { id: 144, skill: "Pharmaceuticals" },
  { id: 145, skill: "Nursing" },
  { id: 146, skill: "Patient Care" },
  { id: 147, skill: "Health Education" },
  { id: 148, skill: "Medical Writing" },
  { id: 149, skill: "Physiotherapy" },
  { id: 150, skill: "Healthcare Compliance" },
  { id: 151, skill: "Surgical Skills" },
  { id: 152, skill: "Dentistry" },
  { id: 153, skill: "Radiology" },
  { id: 154, skill: "Pathology" },
  { id: 155, skill: "Anesthesia" },
  { id: 156, skill: "Healthcare IT" },
  { id: 157, skill: "Telemedicine" },
  { id: 158, skill: "Mental Health" },
  { id: 159, skill: "Nutrition" },
  { id: 160, skill: "Personal Fitness" },
  { id: 161, skill: "Sports Coaching" },
  { id: 162, skill: "Exercise Physiology" },
  { id: 163, skill: "Sports Medicine" },
  { id: 164, skill: "Strength Training" },
  { id: 165, skill: "Yoga" },
  { id: 166, skill: "Pilates" },
  { id: 167, skill: "Martial Arts" },
  { id: 168, skill: "Dance" },
  { id: 169, skill: "Music Theory" },
  { id: 170, skill: "Piano" },
  { id: 171, skill: "Guitar" },
  { id: 172, skill: "Violin" },
  { id: 173, skill: "Singing" },
  { id: 174, skill: "Songwriting" },
  { id: 175, skill: "Music Production" },
  { id: 176, skill: "Audio Engineering" },
  { id: 177, skill: "DJing" },
  { id: 178, skill: "Photography" },
  { id: 179, skill: "Photo Editing" },
  { id: 180, skill: "Videography" },
  { id: 181, skill: "Film Production" },
  { id: 182, skill: "Screenwriting" },
  { id: 183, skill: "Directing" },
  { id: 184, skill: "Cinematography" },
  { id: 185, skill: "Video Post-Production" },
  { id: 186, skill: "3D Animation" },
  { id: 187, skill: "VFX (Visual Effects)" },
  { id: 188, skill: "Sound Design" },
  { id: 189, skill: "Lighting Design" },
  { id: 190, skill: "Set Design" },
  { id: 191, skill: "Acting" },
  { id: 192, skill: "Voice Acting" },
  { id: 193, skill: "Comedy" },
  { id: 194, skill: "Writing" },
  { id: 195, skill: "Editing" },
  { id: 196, skill: "Proofreading" },
  { id: 197, skill: "Copywriting" },
  { id: 198, skill: "Technical Writing" },
  { id: 199, skill: "Journalism" },
  { id: 200, skill: "Blogging" },
  { id: 201, skill: "Creative Writing" },
  { id: 202, skill: "Grant Writing" },
  { id: 203, skill: "Content Creation" },
  { id: 204, skill: "E-commerce" },
  { id: 205, skill: "Salesforce" },
  { id: 206, skill: "Zoho CRM" },
  { id: 207, skill: "Customer Relationship Management" },
  { id: 208, skill: "Business Strategy" },
  { id: 209, skill: "Entrepreneurship" },
  { id: 210, skill: "Business Analytics" },
  { id: 211, skill: "Retail Management" },
  { id: 212, skill: "E-commerce Platforms" },
  { id: 213, skill: "Shopify" },
  { id: 214, skill: "WooCommerce" },
  { id: 215, skill: "Magento" },
  { id: 216, skill: "Product Management" },
  { id: 217, skill: "UX Research" },
  { id: 218, skill: "Customer Experience" },
  { id: 219, skill: "A/B Testing" },
  { id: 220, skill: "Product Marketing" },
  { id: 221, skill: "Lead Generation" },
  { id: 222, skill: "Conversion Rate Optimization" },
  { id: 223, skill: "Growth Hacking" },
  { id: 224, skill: "Digital Advertising" },
  { id: 225, skill: "Google Ads" },
  { id: 226, skill: "Facebook Ads" },
  { id: 227, skill: "Instagram Ads" },
  { id: 228, skill: "Social Media Strategy" },
  { id: 229, skill: "Online Reputation Management" },
  { id: 230, skill: "Influencer Marketing" },
  { id: 231, skill: "Public Relations" },
  { id: 232, skill: "Corporate Communications" },
  { id: 233, skill: "Crisis Management" },
  { id: 234, skill: "Event Planning" },
  { id: 235, skill: "Fundraising" },
  { id: 236, skill: "Non-Profit Management" },
  { id: 237, skill: "Volunteer Management" },
  { id: 238, skill: "Grant Management" },
  { id: 239, skill: "Community Outreach" },
  { id: 240, skill: "Advocacy" },
  { id: 241, skill: "Social Impact" },
  { id: 242, skill: "Sustainability" },
  { id: 243, skill: "Corporate Social Responsibility" },
  { id: 244, skill: "Policy Development" },
  { id: 245, skill: "Legal Research" },
  { id: 246, skill: "Contract Law" },
  { id: 247, skill: "Intellectual Property Law" },
  { id: 248, skill: "Litigation" },
  { id: 249, skill: "Mediation" },
  { id: 250, skill: "Arbitration" },
  { id: 251, skill: "Regulatory Compliance" },
  { id: 252, skill: "Corporate Governance" },
  { id: 253, skill: "Tax Law" },
  { id: 254, skill: "Employment Law" },
  { id: 255, skill: "Criminal Law" },
  { id: 256, skill: "Human Rights Law" },
  { id: 257, skill: "Environmental Law" },
  { id: 258, skill: "International Law" },
  { id: 259, skill: "Immigration Law" },
  { id: 260, skill: "Family Law" },
  { id: 261, skill: "Wills & Trusts" },
  { id: 262, skill: "Estate Planning" },
  { id: 263, skill: "Legal Writing" },
  { id: 264, skill: "Legal Drafting" },
  { id: 265, skill: "Courtroom Procedures" },
  { id: 266, skill: "Jury Selection" },
  { id: 267, skill: "Legal Negotiation" },
  { id: 268, skill: "Forensic Science" },
  { id: 269, skill: "Criminal Investigation" },
  { id: 270, skill: "Fraud Detection" },
  { id: 271, skill: "Cybersecurity Law" },
  { id: 272, skill: "Ethics" },
  { id: 273, skill: "Religious Studies" },
  { id: 274, skill: "Philosophy" },
  { id: 275, skill: "Sociology" },
  { id: 276, skill: "Anthropology" },
  { id: 277, skill: "Psychology" },
  { id: 278, skill: "Behavioral Science" },
  { id: 279, skill: "Neuroscience" },
  { id: 280, skill: "Counseling" },
  { id: 281, skill: "Therapy" },
  { id: 282, skill: "Social Work" },
  { id: 283, skill: "Community Service" },
  { id: 284, skill: "Public Health" },
  { id: 285, skill: "Epidemiology" },
  { id: 286, skill: "Global Health" },
  { id: 287, skill: "Health Policy" },
  { id: 288, skill: "Health Promotion" },
  { id: 289, skill: "Healthcare Management" },
  { id: 290, skill: "Hospital Administration" },
  { id: 291, skill: "Mental Health Advocacy" },
  { id: 292, skill: "Disability Rights" },
  { id: 293, skill: "Public Policy" },
  { id: 294, skill: "Government Relations" },
  { id: 295, skill: "Political Campaigns" },
  { id: 296, skill: "Public Administration" },
  { id: 297, skill: "Legislative Affairs" },
  { id: 298, skill: "Public Speaking" },
  { id: 299, skill: "Speechwriting" },
  { id: 300, skill: "Debate" },
];

export const serviceOptions = [
  { id: 1, serviceName: "Web Design" },
  { id: 2, serviceName: "Web Development" },
  { id: 3, serviceName: "SEO" },
  { id: 4, serviceName: "Graphic Design" },
  { id: 5, serviceName: "Content Writing" },
  { id: 6, serviceName: "App Development" },
  { id: 7, serviceName: "Digital Marketing" },
  { id: 8, serviceName: "E-commerce Solutions" },
  { id: 9, serviceName: "Social Media Management" },
  { id: 10, serviceName: "Cyber Security" },
];

export const priceRangeOptions = [
  { id: 1, priceRange: "$500 - $1,500" },
  { id: 2, priceRange: "$1,000 - $3,000" },
  { id: 3, priceRange: "$300 - $1,000" },
  { id: 4, priceRange: "$200 - $800" },
  { id: 5, priceRange: "$100 - $500" },
  { id: 6, priceRange: "$2,000 - $5,000" },
  { id: 7, priceRange: "$500 - $2,000" },
  { id: 8, priceRange: "$1,500 - $4,000" },
  { id: 9, priceRange: "$300 - $1,200" },
  { id: 10, priceRange: "$400 - $1,500" },
];
